const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "../..");
const OUT_DIR = path.join(ROOT, "web/data");
const SOURCE_WORD_DIR = path.join(ROOT, "tools/dictionary/sources/words");
const LEVEL_ORDER = ["N5", "N4", "N3", "N2", "N1"];
const REQUIRED_FIELDS = ["id", "reading", "writing", "normalizedReading", "playReading", "zh", "level", "script"];

function parseCsvLine(line) {
  const values = [];
  let value = "";
  let inQuotes = false;

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    const next = line[index + 1];

    if (char === '"' && inQuotes && next === '"') {
      value += '"';
      index += 1;
      continue;
    }
    if (char === '"') {
      inQuotes = !inQuotes;
      continue;
    }
    if (char === "," && !inQuotes) {
      values.push(value);
      value = "";
      continue;
    }
    value += char;
  }

  if (inQuotes) throw new Error(`Unclosed CSV quote: ${line}`);
  values.push(value);
  return values;
}

function readCsvRows(filePath) {
  const text = fs.readFileSync(filePath, "utf8").replace(/^\uFEFF/, "").trim();
  if (!text) return [];

  const [headerLine, ...lines] = text.split(/\r?\n/);
  const headers = parseCsvLine(headerLine);
  for (const field of REQUIRED_FIELDS) {
    if (!headers.includes(field)) {
      throw new Error(`${filePath} is missing required field ${field}`);
    }
  }

  return lines.filter(Boolean).map((line, index) => {
    const values = parseCsvLine(line);
    if (values.length !== headers.length) {
      throw new Error(`${filePath}:${index + 2} expected ${headers.length} fields, got ${values.length}`);
    }
    return headers.reduce((row, header, valueIndex) => {
      row[header] = values[valueIndex] || "";
      return row;
    }, {});
  });
}

function wordFileNamesForLevel(level) {
  const prefix = level.toLowerCase();
  return [`${prefix}_core.csv`, `${prefix}_eggrolls.csv`];
}

function normalizeSourceWord(row, expectedLevel, fileName) {
  const word = REQUIRED_FIELDS.reduce((item, field) => {
    item[field] = String(row[field] || "").trim();
    return item;
  }, {});

  if (!word.id) throw new Error(`${fileName}: word id is required`);
  if (word.level !== expectedLevel) {
    throw new Error(`${fileName}: ${word.id} has level ${word.level}, expected ${expectedLevel}`);
  }
  if (!word.playReading) throw new Error(`${fileName}: ${word.id} is missing playReading`);

  return word;
}

function uniqueFirstWordByReadingAndWriting(words) {
  const seen = new Set();
  return words.filter((word) => {
    const key = `${word.playReading}\u0000${word.writing}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function loadWordsByLevel() {
  return LEVEL_ORDER.reduce((map, level) => {
    const rows = wordFileNamesForLevel(level).flatMap((fileName) => {
      const filePath = path.join(SOURCE_WORD_DIR, fileName);
      return readCsvRows(filePath).map((row) => normalizeSourceWord(row, level, fileName));
    });
    map[level] = uniqueFirstWordByReadingAndWriting(rows);
    return map;
  }, {});
}

function writeLevelFile(level, words) {
  const fileName = `word-level-${level.toLowerCase()}.js`;
  const output = [
    "// Generated by tools/dictionary/build_word_level_data.js. Do not edit by hand.",
    "window.FAT_SHIBA_WORD_LEVELS = window.FAT_SHIBA_WORD_LEVELS || {};",
    `window.FAT_SHIBA_WORD_LEVELS.${level} = ${JSON.stringify(words)};`,
    ""
  ].join("\n");
  fs.writeFileSync(path.join(OUT_DIR, fileName), output);
}

function main() {
  const wordsByLevel = loadWordsByLevel();

  for (const level of LEVEL_ORDER) {
    writeLevelFile(level, wordsByLevel[level]);
  }

  const counts = LEVEL_ORDER.map((level) => `${level}:${wordsByLevel[level].length}`).join(" ");
  console.log(`Generated word level data: ${counts}`);
}

main();
